//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Pedido_establecimiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos()
        {
            this.mpedestab = new HashSet<mpedestab>();
        }
    
        public string cod_prod { get; set; }
        public string descripcion { get; set; }
        public string marca { get; set; }
        public string color { get; set; }
        public string modelo { get; set; }
        public string talla { get; set; }
        public string aroma { get; set; }
        public string sabor { get; set; }
        public string unidad_compra { get; set; }
        public decimal contenido { get; set; }
        public string presentacion { get; set; }
        public decimal contenido_presentacion { get; set; }
        public string unidad_presentacion { get; set; }
        public string descripcion_completa { get; set; }
        public string descripcion_corta { get; set; }
        public decimal contenido_lineal { get; set; }
        public string unidad_lineal { get; set; }
        public decimal contenido_area { get; set; }
        public string unidad_area { get; set; }
        public decimal contenido_peso { get; set; }
        public decimal contenido_volumen { get; set; }
        public string unidad_peso { get; set; }
        public string unidad_volumen { get; set; }
        public decimal peso_total { get; set; }
        public float ancho { get; set; }
        public float largo { get; set; }
        public float alto { get; set; }
        public float volumen { get; set; }
        public float ancho_pieza { get; set; }
        public float largo_pieza { get; set; }
        public float alto_pieza { get; set; }
        public short estiba_maxima { get; set; }
        public string criterio_precio_venta { get; set; }
        public decimal iva_interior { get; set; }
        public decimal iva_fronterizo { get; set; }
        public decimal ieps_compra { get; set; }
        public string tipo_ieps_compra { get; set; }
        public decimal ieps { get; set; }
        public string modo_surtido { get; set; }
        public string clave_secofi { get; set; }
        public string clave_ssa { get; set; }
        public string fragilidad { get; set; }
        public byte temperatura { get; set; }
        public bool importado { get; set; }
        public string codigo_analogo { get; set; }
        public string codigo_barras_unidad { get; set; }
        public string codigo_barras_pieza { get; set; }
        public byte garantia_compra { get; set; }
        public byte garantia_fabricacion { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public short caducidad_recepcion { get; set; }
        public short caducidad_venta { get; set; }
        public short caducidad_fabricacion { get; set; }
        public string prioridad_fabricacion { get; set; }
        public string categoria { get; set; }
        public string linea_producto { get; set; }
        public string familia { get; set; }
        public string tipo_producto { get; set; }
        public string clasificacion_productos { get; set; }
        public string grupo_facturacion { get; set; }
        public string clasificacion_carga { get; set; }
        public string comprador { get; set; }
        public string fracciones_por { get; set; }
        public byte decimales { get; set; }
        public string fracciones_por_compras { get; set; }
        public byte decimales_compras { get; set; }
        public string status_producto { get; set; }
        public System.DateTime ultima_modificacion { get; set; }
        public bool ofertable { get; set; }
        public string forma_expresar_inventario { get; set; }
        public decimal minimo_venta { get; set; }
        public decimal multiplo_venta { get; set; }
        public decimal cantidad_precio_promedio { get; set; }
        public string cuenta_contable { get; set; }
        public string contenido_por { get; set; }
        public string sistema_equipos { get; set; }
        public string uso_producto { get; set; }
        public decimal factor_adicional_volumen_carga { get; set; }
        public string tasa_iva_interior { get; set; }
        public string tasa_iva_fronterizo { get; set; }
        public bool precio_venta_automatico { get; set; }
        public bool producto_dependiente { get; set; }
        public decimal minimo_venta_pos { get; set; }
        public decimal multiplo_venta_pos { get; set; }
        public string forma_resurtido_inventario { get; set; }
        public string rango_producto { get; set; }
        public string tabla_comision { get; set; }
        public decimal cantidad_precio_mayoreo { get; set; }
        public string clase_producto { get; set; }
        public bool precio_especifico { get; set; }
        public bool bascula { get; set; }
        public decimal factor_merma { get; set; }
        public string pedaceria { get; set; }
        public bool cantidad_adicional { get; set; }
        public bool control_etiqueta { get; set; }
        public decimal factor_merma_natural { get; set; }
        public bool control_caducidad { get; set; }
        public System.Guid rowguid { get; set; }
        public bool inventario_identificado { get; set; }
        public bool retornable { get; set; }
        public string envase { get; set; }
        public string notas { get; set; }
        public string area { get; set; }
        public Nullable<bool> cruzado { get; set; }
        public string item { get; set; }
        public string tipo_lubricante { get; set; }
        public string viscosidad { get; set; }
        public string norma_oficial_mexicana { get; set; }
        public string usuario_ultima_modificacion { get; set; }
        public decimal peso_ua { get; set; }
        public string grupo_medicamentos { get; set; }
        public string subgrupo_medicamentos { get; set; }
        public byte temperatura2 { get; set; }
        public byte humedad { get; set; }
        public byte humedad2 { get; set; }
        public string rango_temperatura { get; set; }
        public string moneda { get; set; }
        public string tasa_ieps { get; set; }
        public string fabricante { get; set; }
        public string pais_origen { get; set; }
        public string descripcion_adicional { get; set; }
        public string clave_fiscal { get; set; }
        public Nullable<decimal> ieps_cuota_UC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mpedestab> mpedestab { get; set; }
    }
}
