//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Monitor_flujo_de_inventario
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=FlujoInventario")
        {
            SetCommandTimeOut(6000);
        }
        public void SetCommandTimeOut(int Timeout)
        {
            var objectContext = (this as IObjectContextAdapter).ObjectContext;
            objectContext.CommandTimeout = Timeout;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<monitor_flujo_de_inventario_Result> monitor_flujo_de_inventario(Nullable<System.DateTime> fi, Nullable<byte> meses)
        {
            var fiParameter = fi.HasValue ?
                new ObjectParameter("fi", fi) :
                new ObjectParameter("fi", typeof(System.DateTime));
    
            var mesesParameter = meses.HasValue ?
                new ObjectParameter("meses", meses) :
                new ObjectParameter("meses", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<monitor_flujo_de_inventario_Result>("monitor_flujo_de_inventario", fiParameter, mesesParameter);
        }
    }
}
