//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Monitor_flujo_de_inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class monitor_indicadores
    {
        public string Indicador { get; set; }
        public decimal valor_optimo_indicador { get; set; }
        public string operador { get; set; }
    }
}
